# Site settings
title: Sunny Sky Books
email: contact@sunnyskybooks.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sunnyskybooks.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
